# Generated by Django 4.2.1 on 2023-06-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_remove_order_duration_remove_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='star_rating',
            field=models.IntegerField(default=0),
        ),
    ]
