# Generated by Django 4.2.1 on 2023-06-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_hotel_star_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='departure_date',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='package',
            name='orders',
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.package'),
        ),
        migrations.AddField(
            model_name='package',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.country'),
        ),
        migrations.AddField(
            model_name='package',
            name='hotels',
            field=models.ManyToManyField(to='agency.hotel'),
        ),
    ]
