# Generated by Django 4.2.1 on 2023-06-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_employee_package_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
